version: '3.8'

services:
  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - goapp

  goapp:
    container_name: goapp
    image: goapp:1.0.0
    build:
      context: ./backend
      dockerfile: go.dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env

  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  cypress:
    container_name: cypress
    image: cypress/included:13.17.0
    working_dir: /e2e
    environment:
      - CYPRESS_BASE_URL=http://frontend:3000
    volumes:
      - ./cypress:/e2e # Mount the entire cypress folder
    depends_on:
      - nextapp
      - goapp



volumes:
  pgdata: {}
















































































































# services:
#   nextapp:
#     container_name: nextapp
#     image: nextapp:1.0.0
#     build:
#       context: ./frontend
#       dockerfile: next.dockerfile
#     ports:
#       - '3000:3000'
#     environment:
#       - NEXT_PUBLIC_API_URL=http://localhost:8000
#     depends_on:
#       - goapp
#   goapp:
#     container_name: goapp
#     image: goapp:1.0.0
#     build:
#       context: ./backend
#       dockerfile: go.dockerfile
#     environment:
#       - DATABASE_URL=${DATABASE_URL}
#     ports:
#       - '8000:8000'
#     depends_on:
#       - db
#     volumes:
#       - ./.env:/app/.env
#   db:
#     container_name: db
#     image: postgres:15
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#     ports:
#       - '5432:5432'
#     volumes:
#       - pgdata:/var/lib/postgresql/data
# volumes:
#   pgdata: {}
